'use client';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Copy, Send, Plus, CheckCircle, FileText, MessageSquare, Eye, Download, X, Clock } from 'lucide-react';
import api from '@/lib/api';
import { errorMessage } from '@/lib/errors';
import { useAuthStore } from '@/store/auth.store';
import type { DocumentRequest, Requirement, RequestMessage, UploadedDocument } from '@/lib/types';

type Details = { request: DocumentRequest; requirements: Requirement[]; messages: RequestMessage[] };
async function fetchDetails(id: string): Promise<Details> {
  const [request, requirements, messages] = await Promise.all([api.get<DocumentRequest>(`/v1/requests/${id}`), api.get<Requirement[]>(`/v1/requests/${id}/requirements`), api.get<RequestMessage[]>(`/v1/messages/request/${id}`)]);
  return { request: request.data, requirements: requirements.data, messages: messages.data };
}
export default function RequestDetailPage() {
  const { id } = useParams<{ id: string }>();
  const user = useAuthStore(s => s.user);
  const [data, setData] = useState<Details | null>(null);
  const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true);
  const [name, setName] = useState(''); const [instructions, setInstructions] = useState('');
  const [required, setRequired] = useState(true); const [minimum, setMinimum] = useState(1);
  const [message, setMessage] = useState(''); const [internal, setInternal] = useState(false);
  const [review, setReview] = useState<{ id: string; status: string } | null>(null); const [reason, setReason] = useState('');
  const [preview, setPreview] = useState<{ url: string; file: UploadedDocument } | null>(null);
  const [reload, setReload] = useState(0);
  const [templates, setTemplates] = useState<{id:string;name:string}[]>([]);
  const [templateId, setTemplateId] = useState('');
  useEffect(() => { api.get('/v1/templates').then(r => setTemplates(r.data)).catch(e => setError(errorMessage(e))); }, []);
  const canEdit = ['owner', 'admin', 'manager', 'loan_officer'].includes(user?.role || '');
  const canReview = user?.role !== 'read_only';
  useEffect(() => {
    let active = true;
    fetchDetails(id).then(result => { if (active) { setData(result); setError(''); } }).catch(e => { if (active) setError(errorMessage(e)); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [id, reload]);
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview.url); }, [preview]);
  const perform = async (action: () => Promise<unknown>, success: string) => {
    setBusy(true); setError(''); setNotice('');
    try { await action(); setData(await fetchDetails(id)); setNotice(success); return true; }
    catch (e) { setError(errorMessage(e)); return false; } finally { setBusy(false); }
  };
  const addRequirement = async (e: React.FormEvent) => {
    e.preventDefault(); const saved = await perform(() => api.post(`/v1/requests/${id}/requirements`, { name, instructions, required, minFiles: minimum, maxFiles: Math.max(minimum, 10) }), 'Requirement added.');
    if (saved) { setName(''); setInstructions(''); setMinimum(1); }
  };
  const updateStatus = (requirementId: string, status: string, explanation?: string) => perform(() => api.patch(`/v1/requests/requirements/${requirementId}/status`, { status, reason: explanation }), 'Review saved.');
  const sendMessage = async (e: React.FormEvent) => { e.preventDefault(); if (await perform(() => api.post(`/v1/messages/request/${id}`, { message, isInternal: internal }), internal ? 'Internal note saved.' : 'Message sent.')) setMessage(''); };
  const openDocument = async (file: UploadedDocument, download = false) => {
    setError('');
    try { const response = await api.get(`/v1/documents/${file.id}/content`, { responseType: 'blob' }); const url = URL.createObjectURL(response.data);
      if (download) { const a = document.createElement('a'); a.href = url; a.download = file.originalName; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
      else setPreview({ url, file });
    } catch (e) { setError(errorMessage(e, 'Unable to open this document. It may not have passed scanning.')); }
  };
  const copy = async () => { if (!data) return; try { await navigator.clipboard.writeText(`${window.location.origin}/portal/${data.request.portalToken}`); setNotice('Portal link copied.'); } catch { setError('Unable to copy. Use your browser clipboard permissions and retry.'); } };
  const done = data?.requirements.filter(r => ['accepted', 'not_applicable'].includes(r.status)).length || 0;
  const total = data?.requirements.length || 0;
  return <div className="p-4 sm:p-6 lg:p-8 space-y-6 max-w-[1500px] mx-auto">
    <Link href="/requests" className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-slate-800"><ArrowLeft size={16} />Back to requests</Link>
    {error && <div role="alert" className="p-4 rounded-xl bg-red-50 border border-red-200 text-red-800 text-sm">{error}<button onClick={() => setReload(n => n + 1)} className="underline ml-3">Reload</button></div>}
    {notice && <div role="status" className="p-4 rounded-xl bg-emerald-50 border border-emerald-100 text-emerald-800 text-sm">{notice}</div>}
    {loading && <p className="text-center py-12 text-sm text-slate-500">Loading request?</p>}
    {data && <>
      <header className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-[10px] uppercase tracking-widest text-slate-400 font-semibold">Document request</p><h1 className="text-2xl font-bold text-slate-900 mt-2">{data.request.title}</h1><p className="text-sm text-slate-500 mt-2">{data.request.customer?.firstName} {data.request.customer?.lastName} ? {data.request.customer?.email}</p></div><div className="flex flex-wrap gap-2">{data.request.status === 'draft' && canEdit ? <button disabled={busy || !total} onClick={() => perform(() => api.patch(`/v1/requests/${id}/send`), 'Request queued for email delivery.')} className="inline-flex items-center gap-2 bg-[#2d4a7a] text-white px-4 py-3 text-xs font-semibold rounded-xl disabled:opacity-40"><Send size={15} />Send to customer</button> : <button onClick={copy} className="inline-flex items-center gap-2 border border-slate-200 px-4 py-3 text-xs font-semibold rounded-xl bg-white"><Copy size={15} />Copy portal link</button>}<span className="px-4 py-3 rounded-xl bg-blue-50 text-blue-800 text-xs capitalize">{data.request.status.replaceAll('_', ' ')}</span></div></header>
      <section className="bg-white rounded-2xl border border-slate-200 p-5"><div className="flex justify-between gap-4 items-center"><div><h2 className="text-sm font-semibold">Document progress</h2><p className="text-xs text-slate-500 mt-1">{done} of {total} requirements complete</p></div><p className="text-2xl font-bold text-[#2d4a7a]">{total ? Math.round(done / total * 100) : 0}%</p></div><div className="h-2 rounded-full bg-slate-100 mt-4 overflow-hidden"><div className="bg-blue-600 h-full rounded-full" style={{ width: `${total ? done / total * 100 : 0}%` }} /></div></section>
      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6"><div className="xl:col-span-2 space-y-5"><section className="bg-white rounded-2xl border border-slate-200 overflow-hidden"><h2 className="font-semibold p-5 border-b border-slate-100 flex items-center gap-2"><FileText size={18} />Requirements</h2>{!total && <div className="p-5 space-y-3 text-sm text-slate-500"><p>Add a checklist before sending the request.</p>{canEdit && <div className="flex flex-wrap gap-2"><select aria-label="Document template" value={templateId} onChange={e => setTemplateId(e.target.value)} className="border border-slate-200 rounded-lg p-2 max-w-full"><option value="">Choose a template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><button disabled={!templateId || busy} onClick={() => perform(() => api.post(`/v1/templates/${templateId}/apply/${id}`), 'Template applied.')} className="bg-[#2d4a7a] text-white px-3 py-2 rounded-lg text-xs disabled:opacity-40">Apply checklist</button></div>}</div>}{data.requirements.map(r => <article key={r.id} className="p-5 border-b border-slate-100 last:border-0"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold text-sm text-slate-800">{r.name} <span className="text-[10px] text-slate-400 font-normal">{r.required ? 'Required' : 'Optional'} ? {r.minFiles} file(s) minimum</span></h3><p className="text-xs text-slate-500 mt-2 whitespace-pre-wrap">{r.instructions || r.description}</p></div><span className={`text-[10px] px-2.5 py-1.5 h-fit rounded-full capitalize ${r.status === 'accepted' ? 'bg-emerald-50 text-emerald-700' : ['rejected', 'needs_replacement', 'missing'].includes(r.status) ? 'bg-orange-50 text-orange-700' : 'bg-blue-50 text-blue-700'}`}>{r.status.replaceAll('_', ' ')}</span></div>
        <div className="space-y-2 mt-3">{r.documents?.map(file => <div key={file.id} className="bg-slate-50 rounded-lg px-3 py-2.5 flex flex-wrap justify-between items-center gap-3"><div className="min-w-0"><p className="text-xs text-slate-700 break-all">{file.originalName}</p><p className="text-[10px] text-slate-400 mt-1">{(file.fileSize / 1024).toFixed(0)} KB ? {file.malwareScanPassed ? 'Scan passed' : 'Awaiting scan'}</p></div><div className="flex gap-2"><button aria-label={`Preview ${file.originalName}`} onClick={() => openDocument(file)} className="p-2 bg-white border border-slate-200 rounded-lg text-slate-600"><Eye size={14} /></button><button aria-label={`Download ${file.originalName}`} onClick={() => openDocument(file, true)} className="p-2 bg-white border border-slate-200 rounded-lg text-slate-600"><Download size={14} /></button></div></div>)}</div>
        {canReview && !['draft', 'cancelled', 'expired'].includes(data.request.status) && <div className="flex flex-wrap gap-2 mt-4">{['uploaded', 'under_review'].includes(r.status) && <button disabled={busy} onClick={() => updateStatus(r.id, 'accepted')} className="inline-flex gap-1.5 items-center px-3 py-2 rounded-lg text-xs font-medium text-emerald-700 bg-emerald-50"><CheckCircle size={13} />Accept</button>}{(r.documents?.length || 0) > 0 && <button disabled={busy} onClick={() => { setReview({ id: r.id, status: 'needs_replacement' }); setReason(''); }} className="px-3 py-2 rounded-lg text-xs font-medium text-orange-700 bg-orange-50">Request replacement</button>}{r.status !== 'not_applicable' && <button disabled={busy} onClick={() => updateStatus(r.id, 'not_applicable')} className="px-3 py-2 rounded-lg text-xs text-slate-500 border border-slate-200">Not applicable</button>}</div>}
      </article>)}{canEdit && !['completed', 'cancelled', 'expired'].includes(data.request.status) && <form onSubmit={addRequirement} className="p-5 bg-slate-50 space-y-3"><p className="text-xs font-semibold text-slate-700">Add a requirement</p><input aria-label="Requirement name" value={name} onChange={e => setName(e.target.value)} required maxLength={500} placeholder="e.g. Last two months of bank statements" className="w-full border border-slate-200 bg-white rounded-xl p-3 text-sm" /><textarea aria-label="Requirement instructions" value={instructions} onChange={e => setInstructions(e.target.value)} placeholder="Instructions for the borrower" className="w-full border border-slate-200 bg-white rounded-xl p-3 text-sm" /><div className="flex flex-wrap items-center gap-4"><label className="text-xs text-slate-600 flex gap-2 items-center"><input type="checkbox" checked={required} onChange={e => setRequired(e.target.checked)} />Required</label><label className="text-xs text-slate-600 flex gap-2 items-center">Minimum files<input type="number" min={1} max={20} value={minimum} onChange={e => setMinimum(Number(e.target.value))} className="border border-slate-200 rounded-lg p-2 w-16" /></label><button disabled={busy} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-lg bg-[#2d4a7a] text-white text-xs font-semibold ml-auto"><Plus size={14} />Add requirement</button></div></form>}</section></div>
        <div className="space-y-5"><section className="bg-white border border-slate-200 rounded-2xl p-5"><h2 className="font-semibold text-sm mb-4">Request details</h2><p className="text-[10px] uppercase text-slate-400">Due date</p><p className="text-sm text-slate-700 mt-1">{data.request.dueDate ? new Date(data.request.dueDate).toLocaleDateString() : 'No due date'}</p><p className="text-[10px] uppercase text-slate-400 mt-4">Created by</p><p className="text-sm text-slate-700 mt-1">{data.request.creator?.firstName} {data.request.creator?.lastName}</p>{data.request.description && <p className="text-sm text-slate-500 mt-4 whitespace-pre-wrap">{data.request.description}</p>}<p className="mt-5 text-xs text-slate-400 flex items-start gap-2"><Clock size={15} className="shrink-0" />The request completes when all required documents are accepted or marked not applicable.</p></section>
        <section className="bg-white border border-slate-200 rounded-2xl p-5"><h2 className="text-sm font-semibold flex gap-2 items-center"><MessageSquare size={17} />Messages & notes</h2><div className="space-y-3 max-h-80 overflow-y-auto my-4">{!data.messages.length && <p className="text-xs text-slate-400 py-5">No messages yet.</p>}{data.messages.map(m => <div key={m.id} className={`p-3 rounded-xl text-xs whitespace-pre-wrap ${m.isInternal ? 'bg-amber-50 text-amber-900' : 'bg-slate-50 text-slate-700'}`}><p className="text-[10px] text-slate-400 mb-1">{m.isInternal ? 'Internal note ? ' : m.senderType === 'customer' ? 'Borrower ? ' : 'Staff ? '}{new Date(m.createdAt).toLocaleString()}</p>{m.body}</div>)}</div>{canReview && <form onSubmit={sendMessage} className="space-y-3"><label className="text-xs text-slate-500 flex gap-2 items-center"><input type="checkbox" checked={internal} onChange={e => setInternal(e.target.checked)} />Internal note ? staff only</label><textarea aria-label={internal ? 'Internal note' : 'Message customer'} value={message} onChange={e => setMessage(e.target.value)} required maxLength={10000} placeholder={internal ? 'Write an internal note?' : 'Write to your customer?'} className="w-full border border-slate-200 rounded-xl p-3 text-xs" /><button disabled={busy || !message.trim()} className="bg-[#2d4a7a] text-white text-xs font-semibold rounded-lg py-2.5 px-4 disabled:opacity-50">{internal ? 'Save note' : 'Send message'}</button></form>}</section></div>
      </div>
    </>}
    {review && <div className="fixed inset-0 bg-slate-950/50 z-50 p-4 flex items-center justify-center" role="dialog" aria-modal="true" aria-labelledby="replacement-title"><form onSubmit={async e => { e.preventDefault(); if (await updateStatus(review.id, review.status, reason)) setReview(null); }} className="bg-white rounded-2xl p-6 w-full max-w-lg space-y-4"><h2 id="replacement-title" className="text-lg font-semibold">Request a replacement</h2><p className="text-sm text-slate-500">Explain what needs to change. This message will be visible to the borrower.</p><textarea autoFocus aria-label="Replacement reason" required maxLength={2000} value={reason} onChange={e => setReason(e.target.value)} className="w-full border border-slate-200 rounded-xl p-3 text-sm min-h-28" /><div className="flex justify-end gap-3"><button type="button" onClick={() => setReview(null)} className="text-sm text-slate-500">Cancel</button><button disabled={busy} className="bg-[#2d4a7a] text-white text-sm rounded-lg px-4 py-2.5">Save review</button></div></form></div>}
    {preview && <div className="fixed inset-0 z-50 bg-slate-950/70 flex items-center justify-center p-3 sm:p-6" role="dialog" aria-modal="true" aria-label="Document preview"><div className="bg-white rounded-2xl overflow-hidden w-full max-w-5xl h-[85svh] flex flex-col"><div className="p-4 flex gap-4 items-center border-b border-slate-200"><p className="text-sm font-medium truncate flex-1">{preview.file.originalName}</p><a href={preview.url} download={preview.file.originalName} className="text-xs text-blue-700">Download</a><button aria-label="Close preview" onClick={() => setPreview(null)}><X size={20} /></button></div>{['application/pdf', 'image/jpeg', 'image/png'].includes(preview.file.mimeType) ? <iframe title={preview.file.originalName} src={preview.url} className="w-full flex-1 border-0" /> : <div className="p-12 text-center text-sm text-slate-500">Preview is not available for this format. Download the document to review it.</div>}</div></div>}
  </div>;
}
