'use client';
import { useEffect, useState } from 'react';
import api from '@/lib/api';
import { errorMessage } from '@/lib/errors';
import type { StaffUser } from '@/lib/types';
const roles=['admin','manager','loan_officer','processor','underwriter','reviewer','read_only'];
export default function TeamSettings(){
 const [users,setUsers]=useState<(StaffUser&{status:string})[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [reload,setReload]=useState(0);
 const [form,setForm]=useState({firstName:'',lastName:'',email:'',role:'loan_officer'});
 useEffect(()=>{api.get('/v1/users').then(r=>setUsers(r.data)).catch(e=>setError(errorMessage(e)));},[reload]);
 const action=async(fn:()=>Promise<unknown>,message:string)=>{setBusy(true);setError('');setNotice('');try{await fn();setNotice(message);setReload(n=>n+1);return true;}catch(e){setError(errorMessage(e));return false;}finally{setBusy(false);}};
 const invite=async(e:React.FormEvent)=>{e.preventDefault();if(await action(()=>api.post('/v1/users/invite',form),'Invitation queued for email delivery.'))setForm({firstName:'',lastName:'',email:'',role:'loan_officer'});};
 return <section className="bg-white border border-slate-200 rounded-2xl p-5 sm:p-6 space-y-5"><h2 className="text-lg font-semibold text-slate-900">Team members</h2>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{notice&&<p role="status" className="text-sm text-emerald-700">{notice}</p>}<div className="divide-y divide-slate-100">{users.map(u=><div key={u.id} className="py-3 flex flex-wrap gap-3 items-center justify-between"><div><p className="text-sm font-medium">{u.firstName} {u.lastName}</p><p className="text-xs text-slate-400 mt-1">{u.email} ? {u.status}</p></div><div className="flex gap-2 items-center">{u.role==='owner'?<span className="text-xs text-slate-500">Owner</span>:<><select aria-label={`Role for ${u.firstName}`} value={u.role} disabled={busy} onChange={e=>action(()=>api.patch(`/v1/users/${u.id}/role`,{role:e.target.value}),'Role updated.')} className="border border-slate-200 p-2 rounded-lg text-xs">{roles.map(r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select>{u.status!=='inactive'&&<button disabled={busy} onClick={()=>action(()=>api.delete(`/v1/users/${u.id}`),'Access revoked. Existing tokens are no longer accepted.')} className="text-xs text-red-600 px-2 py-2">Deactivate</button>}</>}</div></div>)}</div><form onSubmit={invite} className="border-t border-slate-100 pt-5 grid sm:grid-cols-2 gap-3"><h3 className="text-sm font-semibold sm:col-span-2">Invite a teammate</h3>{(['firstName','lastName','email']as const).map(key=><label key={key} className="text-xs text-slate-500">{key==='firstName'?'First name':key==='lastName'?'Last name':'Email'}<input required type={key==='email'?'email':'text'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} className="block w-full border border-slate-200 p-3 rounded-lg mt-2" /></label>)}<label className="text-xs text-slate-500">Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="block w-full border border-slate-200 p-3 rounded-lg mt-2">{roles.map(r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select></label><button disabled={busy} className="bg-[#2d4a7a] text-white px-5 py-3 rounded-xl text-sm font-semibold sm:col-span-2 disabled:opacity-50">Send invitation</button></form></section>;
}
