'use client';
import { useEffect, useState } from 'react';
import api from '@/lib/api';
import { errorMessage } from '@/lib/errors';
import { useAuthStore } from '@/store/auth.store';
import type { Customer, StaffUser } from '@/lib/types';
type Application = { id: string; applicationNumber: string; applicationType: string; status: string; customer: Customer; assignedUser?: StaffUser };
const statuses = ['draft', 'requested', 'collecting', 'documents_in_review', 'missing_documents', 'ready_for_review', 'approved', 'declined', 'closed'];
export default function ApplicationsPage() {
  const user = useAuthStore(s => s.user);
  const [apps, setApps] = useState<Application[]>([]); const [customers, setCustomers] = useState<Customer[]>([]);
  const [staff, setStaff] = useState<StaffUser[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [reload, setReload] = useState(0); const [form, setForm] = useState({ customerId: '', applicationType: '', assignedUserId: '' });
  const canEdit = ['owner', 'admin', 'manager', 'loan_officer'].includes(user?.role || '');
  useEffect(() => { let active = true; Promise.all([api.get<Application[]>('/v1/applications'), api.get<Customer[]>('/v1/customers')]).then(([a,c]) => { if (active) { setApps(a.data); setCustomers(c.data); } }).catch(e => { if (active) setError(errorMessage(e)); }); return () => { active = false; }; }, [reload]);
  useEffect(() => { if (!user || !['owner','admin','manager'].includes(user.role)) return; api.get<StaffUser[]>('/v1/users').then(r => setStaff(r.data)).catch(e => setError(errorMessage(e))); }, [user]);
  const create = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); setError(''); try { await api.post('/v1/applications', { ...form, assignedUserId: form.assignedUserId || user?.id }); setForm({customerId:'',applicationType:'',assignedUserId:''}); setReload(n=>n+1); } catch(e){setError(errorMessage(e));} finally{setBusy(false);} };
  const status = async (id: string, value: string) => { setError(''); try { await api.patch(`/v1/applications/${id}/status`, { status: value }); setReload(n=>n+1); } catch(e){setError(errorMessage(e));} };
  return <div className="p-4 sm:p-7 space-y-6 max-w-6xl mx-auto"><header><h1 className="text-2xl font-bold text-slate-900">Applications</h1><p className="text-sm text-slate-500 mt-2">Connect customers, document requests and assigned staff.</p></header>{error && <p role="alert" className="bg-red-50 border border-red-200 p-4 rounded-xl text-sm text-red-700">{error}</p>}{canEdit && <form onSubmit={create} className="bg-white border border-slate-200 rounded-2xl p-5 grid sm:grid-cols-2 gap-4"><label className="text-xs text-slate-600">Customer<select required value={form.customerId} onChange={e=>setForm({...form,customerId:e.target.value})} className="block w-full border border-slate-200 rounded-lg p-3 mt-2"><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.firstName} {c.lastName}</option>)}</select></label><label className="text-xs text-slate-600">Application type<input required maxLength={200} value={form.applicationType} onChange={e=>setForm({...form,applicationType:e.target.value})} placeholder="e.g. Residential mortgage" className="block w-full border border-slate-200 rounded-lg p-3 mt-2" /></label><label className="text-xs text-slate-600">Assigned to<select value={form.assignedUserId} onChange={e=>setForm({...form,assignedUserId:e.target.value})} className="block w-full border border-slate-200 rounded-lg p-3 mt-2"><option value="">Me</option>{staff.map(s=><option key={s.id} value={s.id}>{s.firstName} {s.lastName}</option>)}</select></label><button disabled={busy} className="self-end rounded-lg bg-[#2d4a7a] text-white p-3 text-sm font-semibold disabled:opacity-50">Create application</button></form>}<section className="bg-white border border-slate-200 rounded-2xl overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{['Application','Customer','Assigned to','Status'].map(x=><th key={x} className="p-4 font-medium">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{apps.map(a=><tr key={a.id}><td className="p-4"><p className="font-semibold text-slate-800">{a.applicationType}</p><p className="text-[10px] text-slate-400 mt-1 break-all">{a.applicationNumber}</p></td><td className="p-4">{a.customer?.firstName} {a.customer?.lastName}</td><td className="p-4">{a.assignedUser ? `${a.assignedUser.firstName} ${a.assignedUser.lastName}` : 'Unassigned'}</td><td className="p-4"><select aria-label={`Status for ${a.applicationNumber}`} disabled={!canEdit} value={a.status} onChange={e=>status(a.id,e.target.value)} className="border border-slate-200 p-2 rounded-lg">{statuses.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></td></tr>)}{!apps.length && <tr><td colSpan={4} className="p-10 text-center text-slate-400">No applications yet.</td></tr>}</tbody></table></section></div>;
}
